### PR TITLE
Cb 15 Dockerize the Application

### PR DESCRIPTION
**Pull request by asi345**
I dockerized our backend part of the application including the web framework and database. This improvement changed the file structure. Everyone can check if their files are still the same. I also updated README to show how to run in an easier way. Also, please test the code if it is working in your local, to avoid unseen mistakes.

### CODE REVIEW

**Comment by asi345** [comment]
I will fix the conflict tomorrow.

**Comment by asi345** [comment]
Oyle bir conflict ki GitHub bile buradan duzeltme demis

**Comment by asi345** [comment]
I resolved the conflicts, but please check the file changes to ensure we do not lose any commits and changes in the files.

**Review by CodeBlo — APPROVED** [review]
I couldn't see any missing files or any problems with the code.

**Review by kocasariumut — APPROVED** [review]
works as intended

**Review by hamzaakyildiz — DISMISSED** [review]
It works with required functionalities in my local

**Comment by asi345** [comment]
I fixed newly merged files of Eren and Hamza.

**Review by CodeBlo — DISMISSED** [review]

**Review by hamzaakyildiz — APPROVED** [review]
It is working on my local environment

**Review by CodeBlo — APPROVED** [review]

**Review by erencanuysal — APPROVED** [review]
I can't see any problem

**Review by mrabiabrn — APPROVED** [review]

**Review by hamzaakyildiz — APPROVED** [review]

**Pull request merged**
