### PR TITLE
Cb 38 Bugfix/Fixing The Practice App

### PR DESCRIPTION
**Pull request by onurcanavci**
- Fix Corse Problem
- Add express server to frontend
- Refactor likes api and like function in frontend
- Add view number of likes 
- Fix page title
- Add view follower user page and following user page

### CODE REVIEW

**Comment by onurcanavci** [comment]
Add Practice-app link to ReadMe

**Review by erencanuysal — APPROVED** [review]
I tried this on my device and can not see any problem.

**Comment by onurcanavci** [comment]
Fix not liked post error handler in frontend

**Review by ramazanbulut — DISMISSED** [review]
reviewed in zoom meeting

**Review by erencanuysal — DISMISSED** [review]

**Review by asi345 — APPROVED** [review]
I pulled to my local and tested the changes, nothing is wrong.

**Review by erencanuysal — APPROVED** [review]
I tested it. It works as intended

**Review by asi345 — APPROVED** [review]
I pulled to my local and tested the changes, nothing is wrong.

**Review by efesabanogluu — APPROVED** [review]

**Pull request merged**
