### PR TITLE
CB-16

### PR DESCRIPTION
**Pull request by CodeBlo**
Added swagger support and samples for the app

### CODE REVIEW

**Review by hamzaakyildiz — APPROVED** [review]
great improvement

**Review by onurcanavci — APPROVED** [review]
Everything is fine and it is a good example for us. Thanks

**Review by asi345 — APPROVED** [review]
Works really fine, everyone of us can use it

**Review by ramazanbulut — APPROVED** [review]
looks fine

**Review by erencanuysal — APPROVED** [review]
Good

**Pull request merged**
