### PR TITLE
CF-2 Routing and Design Template

### PR DESCRIPTION
**Pull request by onurcanavci**
Add React-Router-Dom and Material UI. Ready for adding new page and creating components

### CODE REVIEW

**Review by ramazanbulut — APPROVED** [review]
nice template
does it contain dark-mode

**Comment by onurcanavci** [comment]
> nice template
> does it contain dark-mode

Yes :)) However, it return the light theme when we refresh page or open new page. I think that open a pull request for not to block your tasks, then I will fix this small problem with using React context

**Review by mrabiabrn — APPROVED** [review]

**Review by CodeBlo — APPROVED** [review]
The templates seems to be helpful. I couldn't see any problems

**Review by kocasariumut — APPROVED** [review]
works as intended

**Pull request merged**
