### PR TITLE
Cb 1

### PR DESCRIPTION
**Pull request by onurcanavci**

### CODE REVIEW

**Review by CodeBlo — APPROVED** [review]

**Review by erencanuysal — APPROVED** [review]
Good!

**Review by kocasariumut — APPROVED** [review]
they work as intended. test will written later

**Review by asi345 — APPROVED** [review]
I see no problem, we can merge this branch.

**Review by ramazanbulut — APPROVED** [review]

**Comment by hamzaakyildiz** [comment]
It looks fine

**Pull request merged**
