### PR TITLE
Kickoff backend

### PR DESCRIPTION
**Pull request by hamzaakyildiz**
Proposed changes
----------------

Backend infrastructure is implemented. 
Database connection is established.
Docker file for Django is created.
docker-compose file for backend and database is created.

Types of changes
----------------

What types of changes does your code introduce?

Set up for infrastructure of backend

Further comments
----------------

added two end point for frontend connection test:
8000:/ 
8000:/test/hello/{input}

### CODE REVIEW

**Review by kocasariumut — APPROVED** [review]
The code works as intended

**Review by efesabanogluu — COMMENTED** [review]
The code works as intended.

**Review by efesabanogluu — APPROVED** [review]
Approved.

**Comment by hamzaakyildiz** [comment]
Backend infrastructure is set up.

**Pull request merged**
