### PR TITLE
Cb 12 Refactor Practice App

### PR DESCRIPTION
**Pull request by onurcanavci**

### CODE REVIEW

**Review by hamzaakyildiz — DISMISSED** [review]
It looks fine

**Review by kocasariumut — DISMISSED** [review]
works as intended

**Review by CodeBlo — APPROVED** [review]

**Review by ramazanbulut — DISMISSED** [review]

**Review by mrabiabrn — APPROVED** [review]
Imports are fixed, it works properly

**Review by CodeBlo — COMMENTED** [review]
We could also add to the readme how to run **a** test file and how to install requirements using requirements.txt

**Review by CodeBlo — APPROVED** [review]

**Review by kocasariumut — APPROVED** [review]
perfect

**Review by efesabanogluu — APPROVED** [review]
amazing

**Review by hamzaakyildiz — APPROVED** [review]
it looks fine

**Pull request merged**
