### PR TITLE
CF-1 Initialize React Project with CRA and Add Axios

### PR DESCRIPTION
**Pull request by onurcanavci**
Created React Project with [create-react-app](https://create-react-app.dev/docs/getting-started) and add [Axios](https://www.npmjs.com/package/axios).

### CODE REVIEW

**Review by erencanuysal — APPROVED** [review]
Nice starting for front end

**Review by hamzaakyildiz — APPROVED** [review]

**Review by ramazanbulut — APPROVED** [review]
nice initial app

**Review by asi345 — APPROVED** [review]
Magnificent!

**Review by mrabiabrn — APPROVED** [review]
An essential part for frontend

**Review by kocasariumut — APPROVED** [review]
perfect

**Pull request merged**
